name: batch-inference
workspace: batch-inference
project: embedding
environment:
  environment_variables:
    # - CUDA_LAUNCH_BLOCKING=1
    # - NCCL_DEBUG=INFO
  image:
    gpu: rag-system:latest
  force_pull_image: false
bind_mounts:
  - host_path: /data/home/sugiyama/rag-system
    container_path: rag-system
  - host_path: /data/home/sugiyama/.cache
    container_path: /root/.cache
  - host_path: /home/sugiyama/github/determined
    container_path: /determined
  - host_path: /home/sugiyama/github/swarm-learning
    container_path: /swarm-learning
resources:
  slots_per_trial: 1
  shm_size: 137438953472
max_restarts: 0
searcher:
  name: single
  max_length: 100
  metric: x
entrypoint: >-
  python3 -m determined.launch.torch_distributed
  python3 embedding_generation.py
