name: embedding
workspace: rag-system
project: embedding
environment:
  # environment_variables:
  #   - CUDA_LAUNCH_BLOCKING=1
  #   - NCCL_DEBUG=INFO
  image:
    gpu: rag-system:latest
  force_pull_image: false
bind_mounts:
  - host_path: /home/hpe01/github/RAG-with-MLDE/rag-system
    container_path: rag-system
  - host_path: /home/hpe01/.cache
    container_path: /root/.cache
resources:
  slots_per_trial: 1
  shm_size: 137438953472
max_restarts: 0
searcher:
  name: single
  max_length: 100
  metric: x
entrypoint: >-
  python3 -m determined.launch.torch_distributed
  python3 index_generation.py
