version: "0.1"

services:
  fastchat-controller:
    image: rag-system:latest
    ports:
      - "20000:20000"
    entrypoint:
      - "python3"
      - "-m"
      - "fastchat.serve.controller"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "20000"
  fastchat-llm-worker:
    volumes:
      - /data/home/sugiyama/.cache/huggingface:/root/.cache/huggingface
    image: rag-system:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint:
      - "python3"
      - "-m"
      - "fastchat.serve.model_worker"
      - "--model-names"
      - "gpt-3.5-turbo,text-davinci-003,text-embedding-ada-002"
      - "--model-path"
      - "lmsys/vicuna-13b-v1.5"
      - "--worker-address"
      - "http://fastchat-llm-worker:21000"
      - "--controller-address"
      - "http://fastchat-controller:20000"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "21000"
      - "--num-gpus"
      - "2"
  fastchat-api-server:
    image: rag-system:latest
    ports:
      - "8000:8000"
    entrypoint:
      - "python3"
      - "-m"
      - "fastchat.serve.openai_api_server"
      - "--controller-address"
      - "http://fastchat-controller:20000"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
