FROM baseimage:latest

ARG PROXY

ENV http_proxy=$PROXY \
    https_proxy=$PROXY

RUN pip install --no-cache -U \
    faiss-gpu \
    langchain \
    openai \
    streamlit

ADD ./rag_utils.py /app/rag_utils.py
ADD ./rag_system.py /app/rag_system.py
ADD ./.streamlit /app/.streamlit

WORKDIR /app
