FROM baseimage:latest

ARG PROXY

ENV http_proxy=$PROXY \
    https_proxy=$PROXY

RUN apt-get update && \
    apt-get install -y daemontools

RUN pip install --no-cache -U \
    determined \
    faiss-gpu \
    llama-index \
    openai \
    pypdf \
    tensorboard
