FROM nvidia/cuda:12.2.0-base-ubuntu22.04

ARG PROXY

ENV http_proxy=$PROXY \
    https_proxy=$PROXY

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git libsndfile1-dev tesseract-ocr espeak-ng python3 python3-pip ffmpeg
RUN python3 -m pip install --no-cache-dir --upgrade pip

RUN python3 -m pip install --no-cache-dir --upgrade torch torchvision torchaudio
RUN python3 -m pip install --no-cache-dir --upgrade transformers accelerate datasets sentencepiece
